services:
  - type: web
    name: school-admission-portal
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn school_portal.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: school-portal-db
          property: connectionString
      - key: ALLOWED_HOSTS
        sync: false
      - key: SECURE_SSL_REDIRECT
        value: True
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: CSRF_COOKIE_SECURE
        value: True

databases:
  - name: school-portal-db
    databaseName: school_portal
    user: portal_user