# Generated by Django 5.2.7 on 2025-10-29 18:53

import admissions.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        default=admissions.models.generate_registration_number,
                        editable=False,
                        help_text="Unique registration number for this application",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        help_text="Current status of the application",
                        max_length=20,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Applicant's date of birth", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        help_text="Applicant's gender",
                        max_length=1,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, help_text="Applicant's nationality", max_length=100
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Residential address"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City of residence", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="State/Province", max_length=100
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="Postal/ZIP code", max_length=20
                    ),
                ),
                (
                    "program_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("undergraduate", "Undergraduate"),
                            ("postgraduate", "Postgraduate"),
                            ("diploma", "Diploma"),
                            ("certificate", "Certificate"),
                        ],
                        help_text="Desired program of study",
                        max_length=50,
                    ),
                ),
                (
                    "course_of_study",
                    models.CharField(
                        blank=True, help_text="Specific course or major", max_length=200
                    ),
                ),
                (
                    "passport_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Upload passport photograph (JPG, PNG only, max 5MB)",
                        null=True,
                        upload_to=admissions.models.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "olevel_result",
                    models.FileField(
                        blank=True,
                        help_text="Upload O'Level result (PDF, JPG, PNG only, max 5MB)",
                        null=True,
                        upload_to=admissions.models.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "birth_certificate",
                    models.FileField(
                        blank=True,
                        help_text="Upload birth certificate (PDF, JPG, PNG only, max 5MB)",
                        null=True,
                        upload_to=admissions.models.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "additional_document_1",
                    models.FileField(
                        blank=True,
                        help_text="Additional supporting document (optional)",
                        null=True,
                        upload_to=admissions.models.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "additional_document_2",
                    models.FileField(
                        blank=True,
                        help_text="Additional supporting document (optional)",
                        null=True,
                        upload_to=admissions.models.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "personal_info_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Step 1: Personal information completed",
                    ),
                ),
                (
                    "program_info_completed",
                    models.BooleanField(
                        default=False, help_text="Step 2: Program information completed"
                    ),
                ),
                (
                    "documents_uploaded",
                    models.BooleanField(
                        default=False, help_text="Step 3: Documents uploaded"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, help_text="Admin notes and comments"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="Date and time of review", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when application was submitted",
                        null=True,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission Application",
                "verbose_name_plural": "Admission Applications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["registration_number"],
                        name="admissions__registr_d0b19c_idx",
                    ),
                    models.Index(
                        fields=["status"], name="admissions__status_134212_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="admissions__created_e86e3c_idx"
                    ),
                ],
            },
        ),
    ]
